services:

  # zensical - documentation
  mkdocs:
    build: .
    ports:
      - 8024:8001 # port mapping for the zensical serve command
    command: zensical serve
    restart: always
    volumes:
      - .:/app/
